services:
  wal-fact-checker:
    build:
      dockerfile: Dockerfile
    container_name: wal-fact-checker
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/app/src
      - ${HOME}/.config/gcloud/application_default_credentials.json:/home/.config/gcloud/application_default_credentials.json:ro
    env_file:
      - .env
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/home/.config/gcloud/application_default_credentials.json
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
